
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('catch').del()
    .then(function () {
      // Inserts seed entries
      return knex('catch').insert([
        { id: 1, 
          user_id: 2,
          fish_id:9,
          region_id:13,
          method_id:1, 
          quantity:3, 
          photo:'1.png',
          weight:'10',
          time:2.5,
          date:'15-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 2, 
          user_id: 2,
          fish_id:1,
          region_id:2,
          method_id:1, 
          quantity:5, 
          photo:'2.png',
          weight:'10',
          time:3,
          date:'17-02-2021',
          description:'I took my son out fishing when he was five years old. After a while of catching some nice smallmouth, my son told me he needed to go "number two". So I told him to hold on while I reeled in my line. I looked over at him and he was already going "number two" in my rear livewell. We had brown trout and smallies that day. I wouldnt trade that memory for anything'
        },
        { id: 3, 
          user_id: 2,
          fish_id:20,
          region_id:7,
          method_id:1, 
          quantity:9, 
          photo:'3.png',
          weight:'10',
          time:3,
          date:'17-03-2021',
          description:'Went down to Oriental Parade for a well earned fishing trip. Lovely Winter weather, blistering wind and icy cold rain ! Caught a lot of seaweed and zero fish. Not a great start to my fishing diary.'
        },
        { id: 4, 
          user_id: 1,
          fish_id:14,
          region_id:3,
          method_id:2, 
          quantity:8, 
          photo:'2.png',
          weight:'10',
          time:3,
          date:'23-08-2020',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 5, 
          user_id: 1,
          fish_id:16,
          region_id:2,
          method_id:1, 
          quantity:6, 
          photo:'1.png',
          weight:'10',
          time:3.5,
          date:'11-03-2020',
          description:'Wet and windy, the fish was not biting. The day Fred face planted at the parking lot'
        },
        { id: 6, 
          user_id: 1,
          fish_id:1,
          region_id:14,
          method_id:2, 
          quantity:5, 
          photo:'3.png',
          weight:'10',
          time:3,
          date:'18-04-2020',
          description:'Got attacked by a bunch of seals! It was the best day of my life'
        },

        { id: 7, 
          user_id: 3,
          fish_id:2,
          region_id:14,
          method_id:3, 
          quantity:2, 
          photo:'4.png',
          weight:'10',
          time:2,
          date:'10-02-2021',
          description:'Caught way lots of fish, Tom and Fred caught lots of fishy!'
        },
        { id: 8, 
          user_id: 3,
          fish_id:3,
          region_id:1,
          method_id:1, 
          quantity:4, 
          photo:'1.png',
          weight:'10',
          time:5,
          date:'12-07-2021',
          description:'The day Sam moved into Edwyn\'s we decided to all go fishing as a flat. Caught heaps of fish for tea.'
        },
        { id: 9, 
          user_id: 3,
          fish_id:8,
          region_id:8,
          method_id:1, 
          quantity:10, 
          photo:'2.png',
          weight:'10',
          time:3.5,
          date:'10-06-2021',
          description:'Took the love of my life fishing. She\'s a keeper!'
        },
        { id: 10, 
          user_id: 4,
          fish_id:20,
          region_id:8,
          method_id:1, 
          quantity:2, 
          photo:'3.png',
          weight:'10',
          time:3,
          date:'10-05-2021',
          description:'Was planning to play some nintendo switch but went fishing instead. Should have just stayed home!'
        },


      
      ]);
    });
};
