
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('catch').del()
    .then(function () {
      // Inserts seed entries
      return knex('catch').insert([
        { id: 1, 
          user_id: '2',
          fish_id:'9',
          region_id:'13',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 2, 
          user_id: '2',
          fish_id:'1',
          region_id:'2',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 3, 
          user_id: '',
          fish_id:'20',
          region_id:'3',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 4, 
          user_id: '1',
          fish_id:'14',
          region_id:'3',
          method_id:'2', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 5, 
          user_id: '1',
          fish_id:'16',
          region_id:'2',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 6, 
          user_id: '1',
          fish_id:'1',
          region_id:'14',
          method_id:'2', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },

        { id: 7, 
          user_id: '3',
          fish_id:'2',
          region_id:'14',
          method_id:'3', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 8, 
          user_id: '3',
          fish_id:'3',
          region_id:'1',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 9, 
          user_id: '4',
          fish_id:'8',
          region_id:'8',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },
        { id: 10, 
          user_id: '4',
          fish_id:'20',
          region_id:'8',
          method_id:'1', 
          quantity:'2', 
          photo:'1.png',
          weight:'10',
          time:'3',
          date:'10-05-2021',
          description:'It was a particular calm day and visibility was great! Even spotted a pod of dolphins and a couple of seals.'
        },


      
      ]);
    });
};
